version: '3.3'
services:
  nnstreamer-dev:
    image: nnstreamer-dev:latest
    runtime: nvidia
    build:
      context: '..'
      dockerfile: 'docker/Dockerfile'
    volumes:
      - '../:/workspace'
      - cargo-registry:/usr/local/cargo/registry
    working_dir: '/workspace'
    environment:
      - DISPLAY=host.docker.internal:0
      - GST_PLUGIN_PATH=/workspace/target/debug
      # Needed for example to load custom metadata
      - LD_LIBRARY_PATH=/workspace/target/debug

volumes:
  cargo-registry:
